Setup FastAPI server and HF Transformers for LLM interfacing using HTTP
skaarkzo-capstone/llm-service pull request #1
Opened 2024-11-15 07:40 UTC by arhamansarii

# JIRA Ticket Link

https://skaarkzo-capstone.atlassian.net/browse/SUSTAIN-20

# Summary of Changes

Created FastAPI server and setup HuggingFace Transformers to interact with LLM and send responses over HTTP.

2024-11-15 20:57 UTC, rakhshankhan commented on app.py
> +app = FastAPI()
I know I said that the architecture might be overkill for this service. But I still think there should be some form of organization. Can we put split creating the application, configuring the application/model, and endpoints separately (similar to file structure and code of the other services)? 

Also thoughts on controller/service again? I'm wondering, when we begin to fine-tune, we shouldn't be doing it directly in the endpoint, so how do we wanna approach organizing any logic for that?

2024-11-15 20:57 UTC, rakhshankhan commented on app.py
> +    input_text: str
Can we also create a separate model folder that has a request folder? Might have other requests later on too depending on how we do finetuning and how we fetch/send the data to the other services.

2024-11-15 20:57 UTC, rakhshankhan commented on app.py
> +    return {"message": "LLM service is running!"}
Likewise, as mentioned above, might just be better to follow some architecture for endpoints to prevent crazy complicated code later on.

2024-11-16 07:23 UTC, zaidokal approved these changes

2024-11-16 07:26 UTC, rakhshankhan requested changes

2024-11-16 07:26 UTC, rakhshankhan commented on app/core/config.py
> +    API_PREFIX: str = "/api/main"
```suggestion
    API_PREFIX: str = "/api/model"
```

2024-11-16 07:26 UTC, rakhshankhan commented on app/core/config.py
> +    # Will add more setting (e.g., DATABASE_URL)
Remove this comment

2024-11-16 07:26 UTC, rakhshankhan commented on app/app.py
> +    app.include_router(api_router, prefix="/api/main")
```suggestion
    app.include_router(api_router, prefix=settings.API_PREFIX")
```

2024-11-16 07:26 UTC, rakhshankhan commented on app/service/service.py
> +model = model.to(device)
anyway we can move this to config.py or create a new model_config.py?

2024-11-16 07:26 UTC, rakhshankhan commented on app/service/service.py
can we rename the file to llm_service

2024-11-16 07:26 UTC, rakhshankhan commented on app/model/dto/model_deto.py
typo in file name, should be prompt_request and go under the "request" folder

2024-11-16 07:26 UTC, rakhshankhan commented on app/service/service.py
> +        return {"response":response_text}
When the response from the model gets more complicated, this will need to become a dto to hold a response object. This is fine for now

2024-11-16 07:26 UTC, rakhshankhan commented on app/api/main/__init__.py
> +api_router.include_router(llm_controller.router, prefix="/llm", tags=["example"])
```suggestion
api_router.include_router(llm_controller.router)
```

2024-11-16 07:26 UTC, rakhshankhan commented on app/api/main/controller/llm_controller.py
> +async def get_example(prompt:TextRequest):
```suggestion
async def generate_prompt(prompt: PromptRequest):
```

2024-11-16 07:26 UTC, rakhshankhan commented on app/model/dto/model_deto.py
> +class TextRequest(BaseModel):
```suggestion
class PromptRequest(BaseModel):
```

2024-11-16 07:35 UTC, arhamansarii commented on app/service/service.py
> +model = model.to(device)
Can we keep this in service? Any future conflict you can see with this approach?

2024-11-16 07:44 UTC, arhamansarii commented on app/service/service.py
> +        return {"response":response_text}
I agree with you. We leave it for now since we don't know what additional fields/attributes the responses could have. This will become obvious as we start fine-tuning the model.

2024-11-16 08:06 UTC, rakhshankhan submitted a review, later dismissed
lgtm!

2024-11-16 08:12 UTC, rakhshankhan approved these changes

2024-11-16 08:16 UTC, zaidokal approved these changes

2024-11-16 08:18 UTC, merged